#![no_std]
#![no_main]
#![allow(unsafe_op_in_unsafe_fn)] // Generated by RTIC 2.1 for Rust 2024.

//! Servo Robot Board Firmware

use defmt_rtt as _;
use panic_halt as _;

#[cfg(feature = "servo")]
use stm32f4xx_hal::pac::interrupt;

defmt::timestamp!("{=u32:us}", {
    // 使用 DWT cycle counter 作为时间戳 (96MHz)
    unsafe {
        let dwt = &*cortex_m::peripheral::DWT::PTR;
        dwt.cyccnt.read() / 96 // 96 cycles = 1 µs
    }
});

mod features;
mod log_macro;
mod platform;

extern crate alloc;

use embedded_alloc::LlffHeap as Heap;

#[global_allocator]
static HEAP: Heap = Heap::empty();

use features::charge::ChargeManager;
use features::power::protection::ProtectionManager;
use servo_robot_protocol::battery_state::BatteryState;
use servo_robot_protocol::config::BoardConfigSnapshot;
use servo_robot_protocol::event::{BoardEvent, ProtectionFlags, StateChangeFlags};
use servo_robot_protocol::frame::{RawFrame, TypedFrame};
use servo_robot_protocol::imu::ImuData;
use servo_robot_protocol::log::LogMessage;
use servo_robot_protocol::power::PowerData;
use servo_robot_protocol::system::SystemInfo;

#[rtic::app(device = stm32f4xx_hal::pac, peripherals = true, dispatchers = [USART6, TIM5, SPI3, SPI4, SPI5])]
mod app {
    use super::*;
    use stm32f4xx_hal::{
        gpio::{Input, Output, PushPull, gpiob, gpioc},
        i2c::I2c,
        pac,
        prelude::*,
        rcc::Config as RccConfig,
    };

    // Use MpuSpiDevice and BusyDelay from platform module (no duplicates)

    // task share data
    #[shared]
    struct Shared {
        i2c1: I2c<pac::I2C1>,
        imu_data: ImuData,
        power_data: PowerData,
        battery_state: BatteryState,
        board_event: BoardEvent,
        prev_board_event: BoardEvent,
        system_info: SystemInfo,
        config: BoardConfigSnapshot,
        pwr_servo_en: gpioc::PC13<Output<PushPull>>,
        bat_ext_out_en: gpioc::PC14<Output<PushPull>>,
        pwr_5v_en: gpioc::PC15<Output<PushPull>>,
        fan_en: gpiob::PB8<Output<PushPull>>,
        pwr_key: gpiob::PB13<Output<PushPull>>,
        charge_mgr: ChargeManager,
        protection_mgr: ProtectionManager,
        ws2812_colors: [platform::ws2812::Color; 3],
        frames_sent: u32,
        uptime_s: u32,
        // 错误计数器
        i2c_errors: u16,
        spi_errors: u16,
        uart_errors: u16,
        usb_errors: u16,
        // PD 请求参数
        pd_request_voltage: u16,
        pd_request_current: u16,
        // 电池温度 (from BQ40Z50, 实际值 = 原始值 / 10)
        temp_battery: i16,
        // IMU 状态
        imu_id: u8,
        _imu_ok: bool,
        usb_dev: features::communication::transport::UsbCompositeDevice<
            'static,
            stm32f4xx_hal::otg_fs::UsbBusType,
        >,
        // UART2 外设 (用于与 Linux 上位机通讯)
        usart2: pac::USART2,
        // 充电器 ACOK 输入 (高电平=充电器已连接)
        bc_acok: gpiob::PB5<Input>,
    }

    // task exclusive data
    #[local]
    struct Local {
        mpu6500: embedded_mpu6500::Mpu6500<
            platform::peripherals::MpuSpiDevice<
                stm32f4xx_hal::spi::Spi<pac::SPI1>,
                gpiob::PB2<Output<PushPull>>,
            >,
        >,
        imu_filter: features::sensing::imu::MahonyFilter,
        usb_rx_buf: [u8; 512],
        usb_rx_pos: usize,
        ota_writer: features::communication::ota::OtaWriter,
    }

    #[init]
    fn init(mut ctx: init::Context) -> (Shared, Local) {
        // Platform: heap + stack watermark
        unsafe { platform::startup::init_heap(&HEAP) };
        platform::startup::paint_stack();

        let dp = ctx.device;

        // 外设时钟使能 (必须在 RCC.constrain() 之前)
        dp.RCC.apb1enr().modify(|_, w| w.usart2en().set_bit());
        dp.RCC
            .apb2enr()
            .modify(|_, w| w.adc1en().set_bit().tim1en().set_bit().syscfgen().set_bit());

        dp.RCC.ahb1enr().modify(|_, w| w.dma2en().set_bit());

        let rcc = dp.RCC.constrain();
        let mut rcc = rcc.freeze(RccConfig::hsi().sysclk(96.MHz()));
        let clocks = rcc.clocks;

        let gpioa = dp.GPIOA.split(&mut rcc);
        let gpiob = dp.GPIOB.split(&mut rcc);
        let gpioc = dp.GPIOC.split(&mut rcc);

        // Platform: UART2 (PA2=TX, PA3=RX, 115200)
        platform::interrupts::init_usart2(&dp.USART2);

        let pwr_servo_en = gpioc.pc13.into_push_pull_output();
        let bat_ext_out_en = gpioc.pc14.into_push_pull_output();
        let pwr_5v_en = gpioc.pc15.into_push_pull_output();
        let fan_en = gpiob.pb8.into_push_pull_output();
        let pwr_key = gpiob.pb13.into_push_pull_output();

        let bc_acok = gpiob.pb5.into_pull_down_input();
        // HUSB238A INT_N: 低有效，配置为上拉输入
        let _husb_int = gpiob.pb14.into_pull_up_input();

        // Platform: EXTI for PB5 (BC_ACOK) and PB14 (HUSB238A INT_N)
        platform::interrupts::configure_exti();

        // Platform: ADC GPIO (PA0, PA1, PA4, PB0, PB1 = analog)
        platform::peripherals::configure_adc_gpio();

        // I2C1 (PB6=SCL, PB7=SDA)
        let scl1 = gpiob.pb6.into_alternate_open_drain();
        let sda1 = gpiob.pb7.into_alternate_open_drain();
        let mut i2c1 = I2c::new(dp.I2C1, (scl1, sda1), 400.kHz(), &mut rcc);

        // Charge: HUSB238A initialization (unmask interrupts)
        features::charge::init::init_husb238a(&mut i2c1);

        // SPI1 (PA5=SCK, PA6=MISO, PA7=MOSI) + CS=PB2
        let sck = gpioa.pa5.into_alternate();
        let miso = gpioa.pa6.into_alternate();
        let mosi = gpioa.pa7.into_alternate();
        let spi1 = stm32f4xx_hal::spi::Spi::new(
            dp.SPI1,
            (Some(sck), Some(miso), Some(mosi)),
            stm32f4xx_hal::spi::Mode {
                polarity: stm32f4xx_hal::spi::Polarity::IdleHigh,
                phase: stm32f4xx_hal::spi::Phase::CaptureOnSecondTransition,
            },
            1.MHz(),
            &mut rcc,
        );
        let cs_mpu = gpiob.pb2.into_push_pull_output();

        // 初始化 MPU6500
        let mpu_spi = platform::peripherals::MpuSpiDevice {
            bus: spi1,
            cs: cs_mpu,
        };
        let mut mpu6500 = embedded_mpu6500::Mpu6500::new(mpu_spi);
        let mut mpu_delay = platform::peripherals::BusyDelay;
        let (who, imu_ok) = features::sensing::init::initialize_mpu(&mut mpu6500, &mut mpu_delay);

        // Platform: USB OTG FS
        let usb_dm = gpioa.pa11.into_alternate();
        let usb_dp = gpioa.pa12.into_alternate();
        let (usb_global, usb_device_periph, usb_pwrclk) =
            (dp.OTG_FS_GLOBAL, dp.OTG_FS_DEVICE, dp.OTG_FS_PWRCLK);
        let usb_periph = stm32f4xx_hal::otg_fs::USB::new(
            (usb_global, usb_device_periph, usb_pwrclk),
            (usb_dm, usb_dp),
            &clocks,
        );
        let usb_bus = platform::peripherals::init_usb_bus(usb_periph);
        let usb_dev = features::communication::init::init_usb(usb_bus);

        // Load config from Flash and restore GPIO states
        let config = platform::flash::load_config().unwrap_or_default();

        // 根据配置恢复 GPIO 状态
        let mut pwr_servo_en = pwr_servo_en;
        let mut bat_ext_out_en = bat_ext_out_en;
        let mut pwr_5v_en = pwr_5v_en;
        features::power::init::restore_power_outputs(
            &mut pwr_servo_en,
            &mut bat_ext_out_en,
            &mut pwr_5v_en,
            &config,
        );

        // Product-facing startup sound using the board-owned buzzer output.
        let mut buzzer = platform::buzzer::Buzzer::new(dp.TIM2);
        features::telemetry::startup_sound::play(&mut buzzer);

        // ADC1 + DMA2 初始化
        platform::adc::init_adc_dma(&dp.ADC1, &dp.DMA2);
        defmt::info!(
            "ADC1 + DMA2 initialized ({} channels)",
            platform::adc::ADC_CHANNEL_COUNT
        );

        // WS2812 LED: TIM1 CH2 (PA9) + DMA2 Stream5
        platform::ws2812::init_tim1_dma(&dp.TIM1);
        defmt::info!("WS2812 initialized (TIM1 CH2 + DMA2 Stream5)");

        // Servo owns UART1 entirely. In builds without the feature this only
        // consumes the PAC token; it does not touch RCC, GPIO, or NVIC.
        features::servo::initialize(dp.USART1, &mut ctx.core.NVIC);

        defmt::info!("Servo Robot Board initialized");

        (
            Shared {
                i2c1,
                imu_data: ImuData::default(),
                power_data: PowerData::default(),
                battery_state: BatteryState::default(),
                board_event: BoardEvent::default(),
                prev_board_event: BoardEvent::default(),
                system_info: SystemInfo::default(),
                config,
                pwr_servo_en,
                bat_ext_out_en,
                pwr_5v_en,
                fan_en,
                pwr_key,
                charge_mgr: ChargeManager::new(),
                protection_mgr: ProtectionManager::new(),
                ws2812_colors: [platform::ws2812::Color::BLACK; 3],
                frames_sent: 0,
                uptime_s: 0,
                i2c_errors: 0,
                spi_errors: 0,
                uart_errors: 0,
                usb_errors: 0,
                pd_request_voltage: 0,
                pd_request_current: 0,
                temp_battery: 0,
                imu_id: who,
                _imu_ok: imu_ok,
                usb_dev,
                usart2: dp.USART2,
                bc_acok,
            },
            Local {
                mpu6500,
                imu_filter: features::sensing::imu::MahonyFilter::new(),
                usb_rx_buf: [0u8; 512],
                usb_rx_pos: 0,
                ota_writer: features::communication::ota::OtaWriter::new(),
            },
        )
    }

    #[idle]
    fn idle(_ctx: idle::Context) -> ! {
        loop {
            cortex_m::asm::wfi();
        }
    }

    // ===== Task 1: IMU (100Hz) =====
    #[task(priority = 4, local = [mpu6500, imu_filter], shared = [imu_data, frames_sent])]
    async fn imu_task(mut ctx: imu_task::Context) {
        let mpu = ctx.local.mpu6500;
        let filter = ctx.local.imu_filter;
        // 100 Hz → dt = 10 ms = 0.01 s
        const IMU_DT: f32 = 0.01;
        match features::sensing::task::read_imu(mpu, filter, IMU_DT) {
            Ok(imu) => {
                ctx.shared.imu_data.lock(|d| *d = imu.clone());
                ctx.shared.frames_sent.lock(|f| *f += 1);
                comm_tx_task::spawn(TypedFrame::Imu(imu)).ok();
            }
            Err(_) => {
                defmt::warn!("MPU6500 read error");
            }
        }
    }

    // ===== Task 2: 电源 (20Hz) =====
    #[task(priority = 3, shared = [i2c1, power_data, protection_mgr, pwr_servo_en, frames_sent, board_event])]
    async fn power_task(mut ctx: power_task::Context) {
        let adc_samples = platform::adc::adc_snapshot();
        let (data, servo_current_ma) = ctx
            .shared
            .i2c1
            .lock(|i2c| features::power::task::sample_power(i2c, &adc_samples));

        // 过流保护检查
        let (flags, should_cut) = ctx
            .shared
            .protection_mgr
            .lock(|pm| features::power::task::check_servo_overcurrent(pm, servo_current_ma));
        if should_cut {
            ctx.shared.pwr_servo_en.lock(|p| p.set_low());
        }
        // 更新 board_event 保护标志
        ctx.shared.board_event.lock(|e| {
            e.protection_flags =
                ProtectionFlags::from_bits(flags.to_u16()).unwrap_or(ProtectionFlags::empty());
        });
        event_flush_task::spawn().ok();

        ctx.shared.power_data.lock(|d| *d = data.clone());
        ctx.shared.frames_sent.lock(|f| *f += 1);
        comm_tx_task::spawn(TypedFrame::Power(data)).ok();
    }

    // ===== Task 4: 电池 (10Hz) =====
    #[task(priority = 3, shared = [i2c1, battery_state, ws2812_colors, frames_sent, temp_battery])]
    async fn bat_task(mut ctx: bat_task::Context) {
        use embedded_bq40z50::Bq40z50;

        let bat_data = ctx.shared.i2c1.lock(|i2c| {
            let mut gauge = Bq40z50::new(&mut *i2c);
            features::sensing::task::read_battery(&mut gauge)
        });

        ctx.shared.battery_state.lock(|d| *d = bat_data.clone());
        ctx.shared.temp_battery.lock(|t| *t = bat_data.temperature);
        ctx.shared.frames_sent.lock(|f| *f += 1);

        let soc = bat_data.percentage;
        ctx.shared.ws2812_colors.lock(|c| {
            c[1] = features::telemetry::indicators::battery_soc_color(soc);
        });
        indicator_flush_task::spawn().ok();

        comm_tx_task::spawn(TypedFrame::Battery(bat_data)).ok();
    }

    // ===== Task 5: 充电管理 (1Hz) =====
    #[task(priority = 2, shared = [i2c1, charge_mgr, board_event, config])]
    async fn charge_task(mut ctx: charge_task::Context) {
        // 从 ADC 读取充电电路 NTC 温度
        let adc_samples = platform::adc::adc_snapshot();
        // 转换为 0.1°C 单位，与 charge_temp_limit/derating 一致
        let charger_temp = features::power::task::charge_temperature_deci_c(&adc_samples);

        let config = ctx.shared.config.lock(|current| current.clone());
        let update = ctx.shared.i2c1.lock(|i2c| {
            ctx.shared.charge_mgr.lock(|manager| {
                features::charge::task::run_charge_cycle(i2c, manager, &config, charger_temp)
            })
        });

        if update.charge_error {
            features::telemetry::indicators::ERROR_STATS.inc_charge();
        }

        ctx.shared
            .board_event
            .lock(|event| event.charge_phase = update.phase);
        event_flush_task::spawn().ok();
    }

    // ===== Task 6: 通讯接收 =====
    #[task(priority = 5, local = [ota_writer], shared = [config, board_event, pwr_servo_en, bat_ext_out_en, pwr_5v_en, fan_en, pwr_key, protection_mgr])]
    async fn comm_rx_task(mut ctx: comm_rx_task::Context, frame: RawFrame) {
        use features::communication::task::ReceiveAction;

        let Some(action) = features::communication::task::decode_inbound(&frame) else {
            return;
        };

        match action {
            ReceiveAction::Reset => {
                defmt::info!("System reset");
                comm_tx_task::spawn(TypedFrame::AckCommand { success: true }).ok();
                cortex_m::peripheral::SCB::sys_reset();
            }
            ReceiveAction::Shutdown => {
                defmt::info!("Shutdown");
                comm_tx_task::spawn(TypedFrame::AckCommand { success: true }).ok();
                ctx.shared.pwr_key.lock(|power_key| power_key.set_low());
            }
            ReceiveAction::StartOta => {
                let flash = unsafe { stm32f4xx_hal::pac::Peripherals::steal() }.FLASH;
                let success = features::communication::ota::start_ota(&flash);
                comm_tx_task::spawn(TypedFrame::AckCommand { success }).ok();
                if success {
                    cortex_m::peripheral::SCB::sys_reset();
                }
            }
            ReceiveAction::ConfigWrite(config) => {
                let write = ctx.shared.config.lock(|current| {
                    features::communication::command::apply_config_write(&config, current)
                });
                let effect = write.effect;

                if let Some(on) = effect.servo_power {
                    ctx.shared
                        .pwr_servo_en
                        .lock(|pin| if on { pin.set_high() } else { pin.set_low() });
                }
                if let Some(on) = effect.power_5v {
                    ctx.shared
                        .pwr_5v_en
                        .lock(|pin| if on { pin.set_high() } else { pin.set_low() });
                }
                if let Some(on) = effect.bat_ext_out {
                    ctx.shared
                        .bat_ext_out_en
                        .lock(|pin| if on { pin.set_high() } else { pin.set_low() });
                }
                if effect.reset_servo_protection {
                    ctx.shared
                        .protection_mgr
                        .lock(|manager| manager.reset_servo_power());
                }
                if effect.reset_5v_protection {
                    ctx.shared
                        .protection_mgr
                        .lock(|manager| manager.reset_5v_power());
                }
                if let Some((flag, value)) = effect.state_flag {
                    ctx.shared
                        .board_event
                        .lock(|event| event.state_change_flags.set(flag, value));
                }

                let flash = unsafe { stm32f4xx_hal::pac::Peripherals::steal() }.FLASH;
                platform::flash::save_config(&flash, &write.snapshot).ok();
                comm_tx_task::spawn(TypedFrame::AckCfgWrite { success: true }).ok();
                event_flush_task::spawn().ok();
            }
            ReceiveAction::ConfigQuery(config_type) => {
                let config = ctx.shared.config.lock(|current| {
                    features::communication::command::get_config_value(current, config_type)
                });
                comm_tx_task::spawn(TypedFrame::AckCfgQuery(config)).ok();
            }
            ReceiveAction::ConfigQueryAll => {
                let config = ctx.shared.config.lock(|current| current.clone());
                comm_tx_task::spawn(TypedFrame::AckCfgQueryAll(config)).ok();
            }
            ReceiveAction::ServoForward(command) => {
                if features::servo::is_enabled() {
                    servo_forward_task::spawn(command).ok();
                } else {
                    features::servo::log_forwarding_disabled();
                }
            }
            ReceiveAction::FirmwareUpdate(block) => {
                let flash = unsafe { stm32f4xx_hal::pac::Peripherals::steal() }.FLASH;
                let acknowledgement = features::communication::task::write_firmware_update(
                    ctx.local.ota_writer,
                    &flash,
                    block.data(),
                );
                comm_tx_task::spawn(acknowledgement).ok();
            }
        }
    }

    // ===== Task 7: 通讯发送 (USB + UART2 双通道) =====
    #[task(priority = 1, shared = [frames_sent])]
    async fn comm_tx_task(mut ctx: comm_tx_task::Context, frame: TypedFrame) {
        let (usb_written, uart_written) =
            features::communication::transport::encode_and_enqueue_dual(&frame);
        if usb_written > 0 || uart_written > 0 {
            ctx.shared.frames_sent.lock(|f| *f += 1);
            if usb_written > 0 {
                tx_flush_task::spawn().ok();
            }
            if uart_written > 0 {
                uart_flush_task::spawn().ok();
            }
        } else {
            defmt::warn!("TX queue full");
        }
    }

    // ===== Board-event flush (triggered, coalescing) =====
    // Producers update the latest state and request a low-priority flush. This
    // is a state notification, not a lossless transition log.
    #[task(priority = 2, shared = [board_event, prev_board_event])]
    async fn event_flush_task(mut ctx: event_flush_task::Context) {
        // 在同一把锁内完成 diff 检查和快照克隆，避免两次读取之间被高优先级任务修改
        let snapshot = ctx.shared.board_event.lock(|cur| {
            let changed = ctx
                .shared
                .prev_board_event
                .lock(|prev| features::telemetry::event::diff_and_update(prev, cur));
            if changed { Some(cur.clone()) } else { None }
        });
        if let Some(e) = snapshot {
            comm_tx_task::spawn(TypedFrame::Event(e)).ok();
        }
    }

    // ===== EXTI9_5 中断 (PB5 = BC_ACOK) =====
    // 上升沿触发，读取引脚状态并同步更新 board_event
    #[task(priority = 3, binds = EXTI9_5, shared = [board_event, bc_acok])]
    fn exti9_5_task(mut ctx: exti9_5_task::Context) {
        // 清除 EXTI5 pending bit (写 1 清除)
        let exti = unsafe { &*stm32f4xx_hal::pac::EXTI::ptr() };
        exti.pr().write(|w| w.pr5().clear_bit_by_one());

        // 读取 BC_ACOK 引脚状态并更新 board_event
        let acok = ctx.shared.bc_acok.lock(|pin| pin.is_high());
        ctx.shared.board_event.lock(|event| {
            features::charge::task::set_charger_connected(event, acok);
        });
        defmt::info!("EXTI9_5: BC_ACOK = {}", acok);
        event_flush_task::spawn().ok();
    }

    // ===== HUSB238A 中断处理任务 =====
    // 读取并清除 HUSB238A 中断锁存，更新 board_event
    #[task(priority = 3, shared = [i2c1, board_event])]
    async fn husb_interrupt_task(mut ctx: husb_interrupt_task::Context) {
        let interrupt = ctx
            .shared
            .i2c1
            .lock(features::charge::task::handle_husb_interrupt);

        // 将 HUSB 中断快照投影到 board_event，随后由 diff 事件任务发送帧。
        if let Some(interrupt) = interrupt {
            ctx.shared.board_event.lock(|event| {
                features::charge::task::apply_husb_interrupt(event, interrupt);
            });

            if interrupt.attach_changed {
                defmt::info!("HUSB238A attachment state changed: {}", interrupt.attached);
            }
            if interrupt.fault {
                defmt::warn!("HUSB238A PD sink fault reported");
            }
            event_flush_task::spawn().ok();
        }
    }

    // ===== EXTI15_10 中断 (PB14 = HUSB238A INT_N) =====
    // 下降沿触发，spawn husb_interrupt_task 处理中断
    #[task(priority = 3, binds = EXTI15_10)]
    fn exti15_10_task(_ctx: exti15_10_task::Context) {
        // 清除 EXTI14 pending bit (写 1 清除)
        let exti = unsafe { &*stm32f4xx_hal::pac::EXTI::ptr() };
        exti.pr().write(|w| w.pr14().clear_bit_by_one());

        defmt::info!("EXTI15_10: HUSB238A INT_N triggered");
        // spawn 异步任务来读取并清除 HUSB238A 中断
        husb_interrupt_task::spawn().ok();
    }

    // ===== Task 9: 日志 =====
    #[task(priority = 1, shared = [config])]
    async fn log_task(mut ctx: log_task::Context, msg: LogMessage) {
        let should_send = ctx
            .shared
            .config
            .lock(|c| features::communication::command::should_send_log(c.tx_log_level, msg.level));
        if should_send {
            comm_tx_task::spawn(TypedFrame::Log(msg)).ok();
        }
    }

    // ===== Task 10: 系统信息 + 温度监控 + 风扇控制 (1Hz) =====
    #[task(priority = 1, shared = [system_info, uptime_s, frames_sent, i2c_errors, spi_errors, uart_errors, usb_errors, pd_request_voltage, pd_request_current, imu_id, protection_mgr, pwr_servo_en, pwr_5v_en, config, ws2812_colors, fan_en, board_event, bc_acok, temp_battery])]
    async fn sys_info_task(mut ctx: sys_info_task::Context) {
        ctx.shared.uptime_s.lock(|t| *t += 1);

        // Feature: read device identity and temperatures
        let device_id = features::telemetry::system_info::get_device_id();
        let uid = features::telemetry::system_info::get_uid();
        let imu_id = ctx.shared.imu_id.lock(|id| *id);
        let (temp_charge, temp_servo, temp_5v, mcu_temp) =
            features::telemetry::task::read_all_temperatures();

        let heap_used = HEAP.used();
        let free_heap_kb = ((platform::startup::HEAP_SIZE.saturating_sub(heap_used)) / 1024) as u16;

        // Lock: read error counters and PD params
        let i2c_errors = ctx.shared.i2c_errors.lock(|e| *e);
        let spi_errors = ctx.shared.spi_errors.lock(|e| *e);
        let uart_errors = ctx.shared.uart_errors.lock(|e| *e);
        let usb_errors = ctx.shared.usb_errors.lock(|e| *e);
        let pd_voltage = ctx.shared.pd_request_voltage.lock(|v| *v);
        let pd_current = ctx.shared.pd_request_current.lock(|c| *c);

        let limits = ctx
            .shared
            .config
            .lock(|config| features::power::task::thermal_limits(config));
        let fan_currently_on = ctx.shared.fan_en.lock(|fan| fan.is_set_high());
        let thermal = ctx.shared.protection_mgr.lock(|manager| {
            features::power::task::evaluate_thermal_control(
                manager,
                temp_charge,
                temp_servo,
                temp_5v,
                limits,
                fan_currently_on,
            )
        });
        if thermal.cut_servo_power {
            ctx.shared.pwr_servo_en.lock(|pin| pin.set_low());
        }
        if thermal.cut_5v_power {
            ctx.shared.pwr_5v_en.lock(|pin| pin.set_low());
        }
        ctx.shared.fan_en.lock(|fan| {
            if thermal.fan_on {
                fan.set_high();
            } else {
                fan.set_low();
            }
        });

        // Lock: update board_event
        let charger_connected = ctx.shared.bc_acok.lock(|pin| pin.is_high());
        let event_update = features::telemetry::task::build_system_event_update(
            thermal.protection_flags,
            thermal.fan_on,
            charger_connected,
            i2c_errors,
            spi_errors,
            uart_errors,
            usb_errors,
        );
        ctx.shared.board_event.lock(|event| {
            event.protection_flags = event_update.protection_flags;
            event
                .state_change_flags
                .set(StateChangeFlags::FAN_ENABLED, event_update.fan_enabled);
            event.state_change_flags.set(
                StateChangeFlags::CHARGER_CONNECTED,
                event_update.charger_connected,
            );
            event.error_flags = event_update.error_flags;
        });
        event_flush_task::spawn().ok();

        // WS2812 LED[0]: charge temperature indicator
        ctx.shared.ws2812_colors.lock(|c| {
            c[0] = features::telemetry::task::charge_temperature_indicator(temp_charge);
        });
        indicator_flush_task::spawn().ok();

        // Feature: assemble SystemInfo
        let uptime_s = ctx.shared.uptime_s.lock(|t| *t);
        let frames_sent = ctx.shared.frames_sent.lock(|f| *f);
        let temp_battery = ctx.shared.temp_battery.lock(|t| *t);
        let info = features::telemetry::task::assemble_system_info(
            features::telemetry::task::SystemInfoInputs {
                device_id,
                uid,
                imu_id,
                uptime_s,
                free_heap_kb,
                i2c_errors,
                spi_errors,
                uart_errors,
                usb_errors,
                frames_sent,
                pd_voltage,
                pd_current,
                temp_servo,
                temp_5v,
                mcu_temp,
                temp_charge,
                temp_battery,
            },
        );

        comm_tx_task::spawn(TypedFrame::System(info)).ok();
    }

    // ===== WS2812 indicator flush =====
    // Sensor tasks update a shared color snapshot. This low-priority task
    // coalesces updates and keeps DMA/TIM work out of sampling paths.
    #[task(priority = 1, shared = [ws2812_colors])]
    async fn indicator_flush_task(mut ctx: indicator_flush_task::Context) {
        let colors = ctx.shared.ws2812_colors.lock(|c| *c);
        platform::ws2812::send_colors(&colors);
    }

    // ===== USB 轮询 (中断) =====
    #[task(priority = 6, binds = OTG_FS, shared = [usb_dev], local = [usb_rx_buf, usb_rx_pos])]
    fn usb_poll_task(mut ctx: usb_poll_task::Context) {
        let rx_buf = ctx.local.usb_rx_buf;
        let rx_pos = ctx.local.usb_rx_pos;

        ctx.shared.usb_dev.lock(|usb_dev| {
            features::communication::task::poll_usb(usb_dev, rx_buf, rx_pos, |frame| {
                comm_rx_task::spawn(frame).ok();
            });
        });
    }

    // ===== USB TX 刷新 =====
    #[task(priority = 5, shared = [usb_dev])]
    async fn tx_flush_task(mut ctx: tx_flush_task::Context) {
        ctx.shared.usb_dev.lock(|usb_dev| {
            features::communication::task::flush_usb(usb_dev);
        });
    }

    // ===== UART2 中断处理 =====
    #[task(priority = 5, binds = USART2, shared = [usart2, uart_errors])]
    fn usart2_irq_task(mut ctx: usart2_irq_task::Context) {
        let had_rx = ctx
            .shared
            .usart2
            .lock(features::communication::task::handle_uart2_irq);
        // 收到 RX 数据后，触发帧解析任务
        if had_rx {
            uart2_rx_check_task::spawn().ok();
        }
    }

    // ===== UART2 RX 帧解析 =====
    #[task(priority = 4)]
    async fn uart2_rx_check_task(_ctx: uart2_rx_check_task::Context) {
        features::communication::task::drain_uart2_frames(|frame| {
            comm_rx_task::spawn(frame).ok();
        });
    }

    // ===== UART2 TX 刷新 =====
    #[task(priority = 5, shared = [usart2])]
    async fn uart_flush_task(mut ctx: uart_flush_task::Context) {
        ctx.shared
            .usart2
            .lock(features::communication::task::flush_uart2);
    }

    // ===== Optional UART1 serial-servo forwarding =====
    // These software tasks remain visible to IDEs in every build. The UART1
    // vector itself is feature-gated outside this RTIC application.
    #[task(priority = 5)]
    async fn servo_forward_task(
        _ctx: servo_forward_task::Context,
        command: servo_robot_protocol::servo::ServoCmdWrapper,
    ) {
        features::servo::task::servo_forward(command.data());
    }

    #[task(priority = 3)]
    async fn servo_rx_check_task(_ctx: servo_rx_check_task::Context) {
        if let Some(wrapper) = features::servo::task::servo_rx_check() {
            comm_tx_task::spawn(TypedFrame::AckServoCmd(wrapper)).ok();
        }
    }

    /// Schedule receive processing from the feature-gated USART1 vector.
    #[cfg(feature = "servo")]
    pub(super) fn spawn_servo_rx_check_from_irq() {
        servo_rx_check_task::spawn().ok();
    }
}

/// USART1 is deliberately outside RTIC so this vector and its NVIC setup do
/// not exist at all when the optional serial-servo capability is disabled.
#[cfg(feature = "servo")]
#[cortex_m_rt::interrupt]
fn USART1() {
    if features::servo::task::handle_usart1_irq() {
        app::spawn_servo_rx_check_from_irq();
    }
}
